import { CallTypes } from "@/constants/call-types";
import { ICall } from "@/lib/interfaces/call-interface";

export const sampleCalls: ICall[] = [
    {
        id: 1,
        date: new Date('2025-01-15T10:00:00'),
        caller: "Alice",
        receiver: "Bob",
        callType: CallTypes.INCOMING,
        duration: 5,
        recorder: "System1",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 2,
        date: new Date('2024-02-01T11:30:00'),
        caller: "Charlie",
        receiver: "Dana",
        callType: CallTypes.OUTGOING,
        duration: 65,
        recorder: "System2",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 3,
        date: new Date('2025-01-05T12:15:00'),
        caller: "Eve",
        receiver: "Frank",
        callType: CallTypes.INCOMING,
        duration: 20,
        recorder: "System3",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 4,
        date: new Date('2025-01-01T13:00:00'),
        caller: "Grace",
        receiver: "Hannah",
        callType: CallTypes.INTERNAL,
        duration: 20,
        recorder: "System1",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 5,
        date: new Date('2025-01-20T14:45:00'),
        caller: "Ian",
        receiver: "Jack",
        callType: CallTypes.OUTGOING,
        duration: 3,
        recorder: "System2",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 6,
        date: new Date('2025-01-25T15:30:00'),
        caller: "Kara",
        receiver: "Liam",
        callType: CallTypes.INCOMING,
        duration: 2,
        recorder: "System3",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 7,
        date: new Date('2025-01-22T16:00:00'),
        caller: "Mona",
        receiver: "Nina",
        callType: CallTypes.INTERNAL,
        duration: 49,
        recorder: "System1",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 8,
        date: new Date('2025-01-18T17:15:00'),
        caller: "Oscar",
        receiver: "Paul",
        callType: CallTypes.OUTGOING,
        duration: 45,
        recorder: "System2",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 9,
        date: new Date('2025-01-13T18:00:00'),
        caller: "Quincy",
        receiver: "Rachel",
        callType: CallTypes.INCOMING,
        duration: 90,
        recorder: "System3",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    },
    {
        id: 10,
        date: new Date('2025-01-09T19:30:00'),
        caller: "Steve",
        receiver: "Tina",
        callType: CallTypes.INTERNAL,
        duration: 120,
        recorder: "System1",
        streamingUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
        downloadUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    }
];